# Generated by Django 2.1.3 on 2018-11-16 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 11, 16, 9, 20, 7, 877169, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
