# Generated by Django 2.1.3 on 2018-11-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181116_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('moderations', 'moderation'), ('active', 'active')], default='moderation', max_length=10),
        ),
    ]
