# Generated by Django 2.1.3 on 2018-11-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='article', width_field=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('moderation', 'moderation'), ('active', 'active')], default='moderation', max_length=10),
        ),
    ]
